// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Canva from "./islands/Canva.tsx";
import * as $Draggable from "./islands/Draggable.tsx";
import * as $PanelOfConfiguration from "./islands/PanelOfConfiguration.tsx";
import * as $PanelOfRows from "./islands/PanelOfRows.tsx";
import * as $Rows_Action_ButtonRow from "./islands/Rows/Action/ButtonRow.tsx";
import * as $Rows_Action_TextActionRow from "./islands/Rows/Action/TextActionRow.tsx";
import * as $Rows_Edit_CalendarRow from "./islands/Rows/Edit/CalendarRow.tsx";
import * as $Rows_Edit_DropdownRow from "./islands/Rows/Edit/DropdownRow.tsx";
import * as $Rows_Edit_InlinePickerRow from "./islands/Rows/Edit/InlinePickerRow.tsx";
import * as $Rows_Edit_InputRow from "./islands/Rows/Edit/InputRow.tsx";
import * as $Rows_Edit_SearchRow from "./islands/Rows/Edit/SearchRow.tsx";
import * as $Rows_Edit_SelectPhotoRow from "./islands/Rows/Edit/SelectPhotoRow.tsx";
import * as $Rows_Edit_TextAreaRow from "./islands/Rows/Edit/TextAreaRow.tsx";
import * as $Rows_Edit_TextSelectRow from "./islands/Rows/Edit/TextSelectRow.tsx";
import * as $Rows_View_InfoRow from "./islands/Rows/View/InfoRow.tsx";
import * as $Rows_View_InputListRow from "./islands/Rows/View/InputListRow.tsx";
import * as $Rows_View_TextRow from "./islands/Rows/View/TextRow.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Canva.tsx": $Canva,
    "./islands/Draggable.tsx": $Draggable,
    "./islands/PanelOfConfiguration.tsx": $PanelOfConfiguration,
    "./islands/PanelOfRows.tsx": $PanelOfRows,
    "./islands/Rows/Action/ButtonRow.tsx": $Rows_Action_ButtonRow,
    "./islands/Rows/Action/TextActionRow.tsx": $Rows_Action_TextActionRow,
    "./islands/Rows/Edit/CalendarRow.tsx": $Rows_Edit_CalendarRow,
    "./islands/Rows/Edit/DropdownRow.tsx": $Rows_Edit_DropdownRow,
    "./islands/Rows/Edit/InlinePickerRow.tsx": $Rows_Edit_InlinePickerRow,
    "./islands/Rows/Edit/InputRow.tsx": $Rows_Edit_InputRow,
    "./islands/Rows/Edit/SearchRow.tsx": $Rows_Edit_SearchRow,
    "./islands/Rows/Edit/SelectPhotoRow.tsx": $Rows_Edit_SelectPhotoRow,
    "./islands/Rows/Edit/TextAreaRow.tsx": $Rows_Edit_TextAreaRow,
    "./islands/Rows/Edit/TextSelectRow.tsx": $Rows_Edit_TextSelectRow,
    "./islands/Rows/View/InfoRow.tsx": $Rows_View_InfoRow,
    "./islands/Rows/View/InputListRow.tsx": $Rows_View_InputListRow,
    "./islands/Rows/View/TextRow.tsx": $Rows_View_TextRow,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
